### ISSUE TITLE
Error when using with eslint-plugin-rxjs

### ISSUE THREAD

**Issue by vitalyiegorov** [dotansimha/graphql-eslint#544]
**Describe the bug**
We have https://www.npmjs.com/package/eslint-plugin-rxjs rules, and with configuration from the docs, we get following error:
```
Error: Error while loading rule 'rxjs/no-async-subscribe': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

**To Reproduce**
1 Setup eslint-plugin-rxjs rules
2 Setup graphql-eslint according to the docs(via overrides)

```
        {
            files: ['*.mutation.ts'],
            processor: '@graphql-eslint/graphql'
        },
        {
            files: ['*.graphql'],
            plugins: ['@graphql-eslint'],
            parser: '@graphql-eslint/eslint-plugin',
            parserOptions: {
                skipGraphQLConfig: true,
                schema: resolve(__dirname, './backends/client-api-backend/schema.graphql')
                // operations: [resolve(__dirname, './components/**/*.graphql')]
            },
            rules: {
                '@graphql-eslint/avoid-duplicate-fields': 'error',
                '@graphql-eslint/avoid-operation-name-prefix': 'error',
                '@graphql-eslint/avoid-typename-prefix': 'error',
                '@graphql-eslint/description-style': 'error',
                '@graphql-eslint/executable-definitions': 'error',
                '@graphql-eslint/fields-on-correct-type': 'error',
                '@graphql-eslint/fragments-on-composite-type': 'error',
                '@graphql-eslint/input-name': 'error',
                '@graphql-eslint/known-argument-names': 'error',
                '@graphql-eslint/known-directives': 'error',
                '@graphql-eslint/known-fragment-names': 'error',
                '@graphql-eslint/known-type-names': 'error',
                '@graphql-eslint/lone-anonymous-operation': 'error',
                '@graphql-eslint/lone-schema-definition': 'error',
                '@graphql-eslint/naming-convention': 'error',
                '@graphql-eslint/no-anonymous-operations': 'error',
                '@graphql-eslint/no-case-insensitive-enum-values-duplicates': 'error',
                '@graphql-eslint/no-deprecated': 'error',
                '@graphql-eslint/no-fragment-cycles': 'error',
                '@graphql-eslint/no-hashtag-description': 'error',
                '@graphql-eslint/no-operation-name-suffix': 'error',
                '@graphql-eslint/no-undefined-variables': 'error',
                '@graphql-eslint/no-unreachable-types': 'error',
                '@graphql-eslint/no-unused-fields': 'error',
                '@graphql-eslint/no-unused-fragments': 'error',
                '@graphql-eslint/no-unused-variables': 'error',
                '@graphql-eslint/one-field-subscriptions': 'error',
                '@graphql-eslint/overlapping-fields-can-be-merged': 'error',
                '@graphql-eslint/possible-fragment-spread': 'error',
                '@graphql-eslint/possible-type-extension': 'error',
                '@graphql-eslint/provided-required-arguments': 'error',
                '@graphql-eslint/require-deprecation-reason': 'error',
                '@graphql-eslint/require-id-when-available': 'error',
                '@graphql-eslint/scalar-leafs': 'error',
                // '@graphql-eslint/selection-set-depth': ['error', { maxDepth: 3 }],
                '@graphql-eslint/strict-id-in-types': 'error',
                '@graphql-eslint/unique-argument-names': 'error',
                '@graphql-eslint/unique-directive-names': 'error',
                '@graphql-eslint/unique-directive-names-per-location': 'error',
                '@graphql-eslint/unique-enum-value-names': 'error',
                '@graphql-eslint/unique-field-definition-names': 'error',
                '@graphql-eslint/unique-fragment-name': 'error',
                '@graphql-eslint/unique-input-field-names': 'error',
                '@graphql-eslint/unique-operation-name': 'error',
                '@graphql-eslint/unique-operation-types': 'error',
                '@graphql-eslint/unique-type-names': 'error',
                '@graphql-eslint/unique-variable-names': 'error',
                '@graphql-eslint/value-literals-of-correct-type': 'error',
                '@graphql-eslint/variables-are-input-types': 'error',
                '@graphql-eslint/variables-in-allowed-position': 'error'
            }
        }
```

**Expected behavior**
GraphQL linter should work.

**Environment:**

- OS:
- "@graphql-eslint/eslint-plugin": "^1.1.4"
- NodeJS: 16.1.0

**Comment by B2o5T** [comment]
Hi, please provide a reproduction repo with minimal dependencies.

**Comment by mhatvan** [comment]
@dotansimha I also just ran into the same problem as the author but with the `@typescript-eslint/no-unnecessary-condition` rule from https://github.com/typescript-eslint/typescript-eslint. I was able to pinpoint the issue down to this plugin.

**Comment by B2o5T** [comment]
@mhatvan I think maybe this is because you configure incorrectly `graphql-eslint` in your `.eslintrc` config, can you share your config ? Also you can try refactor your `eslint` config like I mentioned in this issue https://github.com/dotansimha/graphql-eslint/issues/477#issuecomment-853729018

**Comment by mhatvan** [comment]
I updated the eslint config to look exactly like in the comment, but it still throws the error.

GitHub couldn't handle it, froze the page, so here is the eslint file in a gist: https://gist.github.com/mhatvan/d3ee11e8f3a3ae19e277b9579ee82e07

Maybe you can figure it out ;)

**Comment by B2o5T** [comment]
Nope, it's important that you don't have any rules configured at top level config, and to move all configurations into overrides section. Since JavaScript rules can't run on GraphQL files and vice versa, if you have rules configured at the top level, they will try to also execute for all overrides, as ESLint's configs cascade.

**Comment by mhatvan** [comment]
Wow, that would be a big config change just to make this one rule work. Is there any plan on making the setup a bit more user-friendly? Otherwise I guess I just have to rearrange the whole file.

**Comment by mhatvan** [comment]
Solved it by restructuring eslint files to have all rules inside overrides.

**Comment by vitalyiegorov** [comment]
@mhatvan Could you please provide your working config example? We have moved TS config to overrides but we get:
```
test.mutation.ts
  0:0  error  Parsing error: Syntax Error: Cannot parse the unexpected character "<"
```

TS file includes generics, maybe this is the issue?

**Comment by mhatvan** [comment]
Sorry, absolutely here it is:

https://gist.github.com/mhatvan/7dd6168a54508b4eb224149768e06701

**Comment by varshith257** [comment]
@mcmxcdev Can you please fix the issue as referenced in #2133 

I am worn out to fix this issue for a week.

As referenced here I moved my rules all to top config but same here..I have my graphql code in .tsx for ex:
### directives.ts
`import { gql } from "graphql-tag";

// Place fields alphabetically to ensure easier lookup and navigation.
export const directives = gql`
  directive @auth on FIELD_DEFINITION

  directive @role(requires: UserType) on FIELD_DEFINITION
`;
`

**.eslintric.json after update of moving entire of suggested to override rules :**
{
  "env": {
    "es2022": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "overrides": [
    {
      "files": ["./src/typeDefs/**/*.ts"],
      "processor": "@graphql-eslint/graphql",
      "rules": {}
    },
    {
      "files": ["./src/typeDefs/**/*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "@typescript-eslint/naming-convention": "off"
      }
    },
    {
      "files": ["tests/**/*"],
      "rules": {
        "no-restricted-imports": "off"
      }
    },
    {
      "files": ["./src/index.ts", "./src/utilities/copyToClipboard.ts"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/no-empty-function": "off"
      }
    },
    {
      "files": ["**/*.js", "**/*.jsx"],
      "rules": {}
    }
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "tsconfigRootDir": ".",
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "eslint-plugin-tsdoc", "import"],
  "root": true,
  "rules": {
    "no-restricted-imports": [
      "error",
      {
        "patterns": ["**/src/**"]
      }
    ],
    "import/no-duplicates": "error",
    "tsdoc/syntax": "error",
    "@typescript-eslint/ban-ts-comment": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-inferrable-types": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/naming-convention": [
      "error",
      // Interfaces must begin with Interface or TestInterface followed by a PascalCase name
      {
        "selector": "interface",
        "format": ["PascalCase"],
        "prefix": ["Interface", "TestInterface"]
      },
      // Type Aliases must be in PascalCase
      {
        "selector": ["typeAlias", "typeLike", "enum"],
        "format": ["PascalCase"]
      },
      {
        "selector": "typeParameter",
        "format": ["PascalCase"],
        "prefix": ["T"]
      },
      {
        "selector": "variable",
        "format": ["camelCase", "UPPER_CASE"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "parameter",
        "format": ["camelCase"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "function",
        "format": ["camelCase"]
      },
      {
        "selector": "memberLike",
        "modifiers": ["private"],
        "format": ["camelCase"],
        "leadingUnderscore": "require"
      },
      { "selector": "variable", "modifiers": ["exported"], "format": null }
    ],
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/consistent-type-assertions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-function-return-type": "error"
  }
}

### Error:
`
C:\Users\91970\Desktop\talawa\talawa-api>npm run lint:check

> talawa-api@1.0.0 lint:check
> eslint . --max-warnings=1500


Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Error while loading rule '@typescript-eslint/consistent-type-assertions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting C:\Users\91970\Desktop\talawa\talawa-api\src\typeDefs\directives.ts\0_document.graphql
    at throwError (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:39:11)
    at getParserServices (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:23:9)
    at create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\eslint-plugin\dist\rules\consistent-type-assertions.js:90:61)
    at Object.create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:38:20)
    at createRuleListeners (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:895:21)
    at C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1003:34)
    at Linter._verifyWithoutProcessors (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1355:31)
    at Linter._verifyWithConfigArray (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1807:21)
(node:32300) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

C:\Users\91970\Desktop\talawa\talawa-api>`
