### ISSUE TITLE
Lint command crashing with `extend type` syntax

### ISSUE THREAD

**Issue by mhatvan** [dotansimha/graphql-eslint#561]
**Describe the bug**

When I run linting over a directory that contains a `.graphql` file with [extend type](https://stackoverflow.com/a/56204966/6864124) syntax, eslint crashes with the following error and stacktrace:

```
TypeError: type.getInterfaces is not a function
Occurred while linting /home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/libs/webmobile-graphql/src/localSchemas/pagination.graphql:1
    at collectFrom (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2959:44)
    at Array.forEach (<anonymous>)
    at collectFromInterfaces (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2992:24)
    at collectFrom (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2955:17)
    at Array.forEach (<anonymous>)
    at collectFrom (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2963:33)
    at collectFromOutputType (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2996:9)
    at collectFromField (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2976:9)
    at collectFromFieldMap (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2972:13)
    at collectFrom (/home/markus/Applications/Webdevelopment/Freelancing/MediaMarktSaturn/webmobile-pwa/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:2954:17)
```

I didn't write that code, but the file contains only `extend type Query` without importing the `type Query` to extend from, so it might not be able to reference it correctly and the issue is on our side. 

**To Reproduce**
- use extend type in a `.graphql` file
- lint over it

**Expected behavior**

Lint passes without error

**Environment:**

- OS: Ubuntu 21.04
- `@graphql-eslint/...`: 1.1.4
- NodeJS: 14.17.2

**Comment by B2o5T** [comment]
Hi @mhatvan and thank you for your report! I think the issue goes from `no-unreachable-types` rule, can you try this alpha version `1.1.5-alpha-8344a53.0` and tell if you have still problem ?

**Comment by mhatvan** [comment]
With the alpha version, it crashes first with `Error: Error while loading rule '@graphql-eslint/no-unused-fields': Rule 'no-unused-fields' requires 'parserOptions.operations' to be set and loaded.`

We do have `parserOptions.operations` set.

If I deactivate `@graphql-eslint/no-unused-fields` temporarily, I run into the same error as reported above.

One thing to note though: we are running on GraphQL 14.7.0 still, going to be switching to v15 in a couple of days, if that can be the issue.

**Comment by B2o5T** [comment]
Can you make a reproduction repo with minimal dependencies and I will help you 😉

**Comment by mhatvan** [comment]
We are now running on `graphql` 15.5.1 and `@graphql-eslint/eslint-plugin` 2.0.0 and it works ;)

Thank you!
